// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project CashAdvance
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faCashAdvance from '@/i18n/cash-advance/fa.json';
import enCashAdvance from '@/i18n/cash-advance/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'cash-advance': faCashAdvance,
  },
  en: {
  'cash-advance': enCashAdvance,
  },
} as const;
